backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: doc
    label: Doc
    folder: content/docs
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - label: Category
        name: category
        widget: select
        options: ["Getting Started", "Guides", "FAQ"]
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "about"
        file: content/pages/home.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
