backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - label: "Config"
    name: "config"
    files:
    - name: doc-category
      label: Doc Category
      file: content/doc-categories.yml
      fields:
        - {label: Name, name: name, widget: string}
  - name: doc
    label: Doc
    folder: content/docs
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - label: Category
        name: category
        widget: relation
        collection: doc-category
        search_fields: ['name']
        value_field: ['name']
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "about"
        file: content/pages/home.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
